version: '3'
services:
  frontend:
    build: ./docker/frontend
    working_dir: /myapp
    volumes:
      - ./docker/frontend:/myapp
      - node_modules_volume:/myapp/node_modules
    ports:
      - "3000:3000"
    command: yarn dev
volumes:
  node_modules_volume:
