version: '3'
services:
  frontend:
    build: ./docker/frontend
    working_dir: /myapp
    environment:
      API_BASE_URL: "${API_BASE_URL}"
    volumes:
      - ./docker/frontend:/myapp
      - node_modules_volume:/myapp/node_modules
    ports:
      - "3000:3000"
    command: yarn dev
  api:
    build: ./docker/api
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "${GOOGLE_APPLICATION_CREDENTIALS}"
    stdin_open: true
    tty: true
    volumes:
      - ./api:/myapp
    ports:
      - "8080:8080"
    command: ./wait-for-it.sh db:3306 -- go run main.go
    depends_on:
      - "db"
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: my-scrapbook
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  node_modules_volume:
  db-data:
    driver: local
