version: '3'
services:
  frontend:
    build: ./docker/frontend
    working_dir: /myapp
    volumes:
      - ./docker/frontend:/myapp
      - node_modules_volume:/myapp/node_modules
    ports:
      - "3000:3000"
    command: yarn dev
  api:
    build: ./docker/api
    stdin_open: true
    tty: true
    volumes:
      - ./src/api:/myapp/src/api
    ports:
      - "8080:8080"
    command: go run src/api/main.go
volumes:
  node_modules_volume:
